### ISSUE TITLE
Compatibility with Auto Research

### ISSUE THREAD

**Issue by dz9c92** [LovelySanta/FactorioMod-MoreScience#1]
This isn't a bug at all but I was wondering if there was anything that could be done about the missing research icons in the auto research mod. Screenshot: http://prntscr.com/k3nxsw  It seems the author has added more compatibility between his mod and others in the past and a few other mods that I personally use have icons in the GUI that do show up but cant get yours' to. I was doing some digging in the code (novice to coding) and I think the problem may have something to do with the fact that the icons folder in your mod has subfolders for the science icons and maybe that his mod only looks at the main folder (tool.icon).  This is the file I believe I should be looking at? https://github.com/canidae/factorio/blob/master/auto-research/data-final-fixes.lua    Would it be best to specify your mod folders in his mod or to add icons to the main icon folder of your mod? Feel free to ignore/delete this post, wanted to see if you were willing to take a look at it for me briefly but this may not be the right place,  thank you.

**Comment by LovelySanta** [comment]
Hi,

As you can see [auto-research/data-final-fixes.lua#7](https://github.com/canidae/factorio/blob/master/auto-research/data-final-fixes.lua#L7) he only puts the tool.icon as filename. The issue is that my potions are made of multiple images, and so [my tools aka science packs](https://github.com/LovelySanta/FactorioMod-MoreScience/blob/master/prototypes/item/regular-science-pack.lua#L10-L22) have the attribute icons set instead of icon.

So this is an issue on his end, i'll open an issue on his github page.

Kind regards,
lovely_santa

**Comment by dz9c92** [comment]
Thank you very much for your help sir. I'm still learning little by little, I appreciate your professionalism and patience as well as your Factorio mods. Have a good day.

**Comment by LovelySanta** [comment]
I'm glad i could help, trying to share my knowledge and creations with others :)
